name = "ElasticPDMats"
uuid = "2904ab23-551e-5aed-883f-487f97af5226"
authors = ["Johanni Brea <jbrea@users.noreply.github.com>"]
version = "0.2.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"

[compat]
julia = "1"
MacroTools = "0.5"
PDMats = "0.10, 0.11"
